import '@/app/globals.css'
import '../../public/fonts/fonts.css'
import { Inter } from 'next/font/google'

// Partes
import Header from '@/components/header'
import Footer from '@/components/footer'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Escuela',
  description: 'Generated by create next app',
}

export default async function RootLayout({ children }) {


  return (
    <html lang="es">
      <body className={`bg-slate-100`} >
        <Header />
        <main className="mx-10 my-20 h-fit">
          {children}
        </main>
        <Footer />
      </body>
    </html>
  )
}
